---
- name: Install Prometheus
  become: yes
  ansible.builtin.shell: |
    curl -LO https://github.com/prometheus/prometheus/releases/download/v2.48.1/prometheus-2.48.1.linux-amd64.tar.gz
    tar -xzf prometheus-2.48.1.linux-amd64.tar.gz
    mv prometheus-2.48.1.linux-amd64 /usr/local/prometheus
    ln -sf /usr/local/prometheus/prometheus /usr/local/bin/prometheus
    ln -sf /usr/local/prometheus/promtool /usr/local/bin/promtool

- name: Create Prometheus user and group
  ansible.builtin.user:
    name: prometheus
    shell: /usr/sbin/nologin

- name: Set ownership of Prometheus directories
  ansible.builtin.file:
    path: "/usr/local/prometheus"
    state: directory
    owner: prometheus
    group: prometheus
    recurse: yes

- name: Configure Prometheus as a service
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/prometheus --config.file=/usr/local/prometheus/prometheus.yml --storage.tsdb.path=/usr/local/prometheus/data

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start Prometheus
  ansible.builtin.systemd:
    daemon_reload: yes
    name: prometheus
    enabled: yes
    state: started

- name: Configure Prometheus
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: /usr/local/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
